version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: zerophp_mysql
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zero
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - zerophp_network

  web:
    build: .
    container_name: zerophp_web
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - zerophp_network

networks:
  zerophp_network:
    driver: bridge

volumes:
  mysql_data: